### ISSUE TITLE
Love your work!

### ISSUE THREAD

**Issue by it33** [JLospinoso/matterbot#1]
Hi @JLospinoso, 

Really love, love, love what you're building here and all your work. We saw your information come in on this project a while ago and we're just now finalizing the announce for Mattermost 3.2 where we talk about the top projects that have come up since the last release. 

We're kind of embarrassed to say this, and weren't sure how to approach you, but the term "matterbot" is something that we've been planning to use in the product itself. 

While we want to let everyone know about what you're doing and get this project out to our community, we're worried about creating confusion when there's a matterbot that people interact with in the product. 

That said, you and [other folks in the community](https://github.com/LPgenerator/mattermost_bot) area out ahead of us on bots, by far. 

I wondered if you'd be open to joining our [integrations channel](https://pre-release.mattermost.com/core/channels/integrations) to discuss the best way to tell people about your work, and have people building on it, while avoiding potential confusion around naming? 

Sorry it took so long to reach out, we just weren't sure how to approach you...

**Comment by JLospinoso** [comment]
Done!
